### ISSUE TITLE
App crashes after updating to new package

### ISSUE THREAD

**Issue by codingcartooningcpa** [LottieFiles/dotlottie-ios#29]
My app starting crashing upon implementation of the new dotLottie package. I believe it is isolated to one of my main animations that ran smoothly and never crashed with the previous dotLottie package. I created an empty project and added my animation assets to the main asset bundle to isolate the issue and found the following:

Here is the SwiftUI code to load from an animation (.lottie / .json) from the main asset bundle:

import SwiftUI
import DotLottie

struct ContentView: View {
    var animation = DotLottieAnimation(fileName: "fish-animation", config: AnimationConfig(autoplay: true, loop: true))
    
    var body: some View {
        VStack {
            animation.view()
        }
    }
}

1) Using the animation as a .json file, the app crashes after 10 seconds and points to the following function as the culprit:

open func render() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_dotlottie_player_fn_method_dotlottieplayer_render(self.uniffiClonePointer(), $0)
        })
    }

In the debug console, these errors are posted:
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...

2) Using the animation as a converted .lottie file, the animation never plays and this error appears in the debug console:
Loading from bundle failed for both .json and .lottie versions of your animation: fileNotFound(animationName: "fish-animation", extensionName: "lottie")

3) Using optimized lottie, the following error:
Loading from bundle failed for both .json and .lottie versions of your animation: fileNotFound(animationName: "optimized-fish-animation", extensionName: "lottie")

I attached the .json file for reference. I used https://lottiefiles.com/tools/lottie-json-to-optimized-lottie-json to convert this file to .lottie and optimized .lottie.
[fish-animation.json](https://github.com/user-attachments/files/16286305/127588-fish-animation.json)

Please let me know if this issue can be resolved so I can continue using this animation. Thank you

**Comment by samuelOsborne** [comment]
Thanks for creating this issue @codingcartooningcpa there is indeed an issue with that animation, I will look in to why this is happening and get back to you, cheers!

**Comment by codingcartooningcpa** [comment]
Thank you for looking into this!

**Comment by samuelOsborne** [comment]
@codingcartooningcpa I believe this issue is fixed on the latest version of the player, im not experiencing any crashes on my end. Could you please try on yours and let me know? 

Cheers

**Comment by codingcartooningcpa** [comment]
Thank you for following up. Unfortunately, the fish-animation as either a .json or .lottie still crashes in the simulator and on my device. The error in the debug console points to the render function. I made sure to update my packages before running.

The second file I attached works properly now as a .json and .lottie. 

In the meantime, I decided to use a different animation in my app instead of the one that seems to be causing some issues.
